/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.pbo;

import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author destria
 */
public class Data_Pelanggan_Offline extends javax.swing.JFrame {
    
    private static final java.  util.logging.Logger logger = java.util.logging.Logger.getLogger(Data_Pelanggan_Offline.class.getName());

    public Data_Pelanggan_Offline() {
        initComponents();
        table();
        setStatusDropdown();
    }
    
    private void table() {
        try {
            List<OfflineSistem> list = OfflineSistem.loadOffline();
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);

            for (OfflineSistem p : list) {
            model.addRow(new Object[]{
                p.getId(),           // ← ini ID asli database
                p.getNama(),
                p.getTanggal(),
                p.getKategori(),
                p.getBerat(),
                p.getTotal(),
                p.getStatus()
            });
}


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    
    private void setStatusDropdown() {
        JComboBox<String> cb = new JComboBox<>();
        cb.addItem("Diproses");
        cb.addItem("Selesai");

        jTable2.getColumnModel().getColumn(6)
                .setCellEditor(new DefaultCellEditor(cb));

        // untuk update otomatis ke database
        jTable2.getModel().addTableModelListener(e -> {
            int row = e.getFirstRow();
            int col = e.getColumn();

            if (col == 6) { // kolom status
                String statusBaru = jTable2.getValueAt(row, col).toString();
                int id = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
          
                try {
                    DataPelangganOfflineSistem.updateStatus(id, statusBaru);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this,
                            "Gagal update status: " + ex.getMessage());
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ButtonTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ButtonDashboard = new javax.swing.JButton();
        ButtonReservasiOffline = new javax.swing.JButton();
        ButtonReservasiOnline = new javax.swing.JButton();
        ButtonWilayah = new javax.swing.JButton();
        ButtonLaporanPemasukan = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        ButtonKategori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 217, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 648));

        jPanel2.setBackground(new java.awt.Color(245, 239, 235));
        jPanel2.setPreferredSize(new java.awt.Dimension(1070, 590));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Tanggal", "Kategori", "Berat Cucian", "Total Harga", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 65, 86));
        jLabel1.setText("Data Pelanggan");

        ButtonTambah.setText("➕ Add Cust");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonTambah)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(460, 460, 460))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambah))
                .addGap(70, 70, 70))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 65, 86));
        jLabel2.setText("BackBurn Laundry");

        ButtonDashboard.setBackground(new java.awt.Color(245, 239, 235));
        ButtonDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonDashboard.setForeground(new java.awt.Color(75, 111, 127));
        ButtonDashboard.setText("Dashboard");
        ButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDashboardActionPerformed(evt);
            }
        });

        ButtonReservasiOffline.setBackground(new java.awt.Color(245, 239, 235));
        ButtonReservasiOffline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonReservasiOffline.setForeground(new java.awt.Color(75, 111, 127));
        ButtonReservasiOffline.setText("Reservasi Offline");
        ButtonReservasiOffline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReservasiOfflineActionPerformed(evt);
            }
        });

        ButtonReservasiOnline.setBackground(new java.awt.Color(245, 239, 235));
        ButtonReservasiOnline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonReservasiOnline.setForeground(new java.awt.Color(75, 111, 127));
        ButtonReservasiOnline.setText("Reservasi Online");
        ButtonReservasiOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReservasiOnlineActionPerformed(evt);
            }
        });

        ButtonWilayah.setBackground(new java.awt.Color(245, 239, 235));
        ButtonWilayah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonWilayah.setForeground(new java.awt.Color(75, 111, 127));
        ButtonWilayah.setText("Wilayah");
        ButtonWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWilayahActionPerformed(evt);
            }
        });

        ButtonLaporanPemasukan.setBackground(new java.awt.Color(245, 239, 235));
        ButtonLaporanPemasukan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonLaporanPemasukan.setForeground(new java.awt.Color(75, 111, 127));
        ButtonLaporanPemasukan.setText("Laporan Pemasukan");
        ButtonLaporanPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLaporanPemasukanActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(245, 239, 235));
        ButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonLogout.setForeground(new java.awt.Color(75, 111, 127));
        ButtonLogout.setText("Logout");
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        ButtonKategori.setBackground(new java.awt.Color(245, 239, 235));
        ButtonKategori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonKategori.setForeground(new java.awt.Color(75, 111, 127));
        ButtonKategori.setText("Kategori");
        ButtonKategori.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonKategori.setBorderPainted(false);
        ButtonKategori.setPreferredSize(new java.awt.Dimension(95, 30));
        ButtonKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(1084, 1096, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonReservasiOffline, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonReservasiOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLaporanPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonReservasiOffline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonReservasiOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonLaporanPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDashboardActionPerformed
        new DashboardAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonDashboardActionPerformed

    private void ButtonReservasiOfflineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReservasiOfflineActionPerformed
        new Data_Pelanggan_Offline().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonReservasiOfflineActionPerformed

    private void ButtonReservasiOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReservasiOnlineActionPerformed
        new Data_Pelanggan_Online().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonReservasiOnlineActionPerformed

    private void ButtonWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWilayahActionPerformed
        new WilayahGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonWilayahActionPerformed

    private void ButtonLaporanPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLaporanPemasukanActionPerformed
        new LaporanPemasukan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonLaporanPemasukanActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        new ReservasiOfflineGUI().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKategoriActionPerformed
        new Kategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Data_Pelanggan_Offline().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonKategori;
    private javax.swing.JButton ButtonLaporanPemasukan;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonReservasiOffline;
    private javax.swing.JButton ButtonReservasiOnline;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JButton ButtonWilayah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
