/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.pbo;

/**
 *
 * @author stevani eka putri
 */
public class ReservasiOfflineGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservasiOfflineGUI.class.getName());

    /**
     * Creates new form Offline
     */
    public ReservasiOfflineGUI() {
        initComponents();
        overrideComboKategori();
    }
    
    private void simpan() {
    try {
        String nama = IsiNamaPelanggan.getText().trim();

        java.util.Date utilDate = (java.util.Date) IsiTanggal.getValue();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        // ENUM -> nama database
        String kategoriText = IsiKategori.getSelectedItem().toString().trim().toLowerCase()
                .replace(" ", "_")
                .replace("+", "_plus_")
                .replace("__", "_");

        // dapatkan id & harga dari DB
        int idKategori = OfflineSistem.getIdKategori(kategoriText);
        double hargaPerKg = OfflineSistem.getHargaKategori(kategoriText);

        double berat = Double.parseDouble(IsiBeratCucian.getText().trim());
        double total = berat * hargaPerKg;

        String status = "diproses";

        OfflineSistem.tambah(nama, sqlDate, idKategori, berat, total, status);

        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan berhasil disimpan!");
        new Data_Pelanggan_Offline().setVisible(true);
        this.dispose();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
    }
    }
    
    private void overrideComboKategori() {
    IsiKategori.removeAllItems();
    IsiKategori.addItem("cuci_kering");
    IsiKategori.addItem("setrika");
    IsiKategori.addItem("cuci_setrika");
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IsiNamaPelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IsiKategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        IsiBeratCucian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        IsiTanggal = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        ButtonSimpan = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 239, 235));
        jPanel1.setForeground(new java.awt.Color(245, 239, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 648));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(126, 90, 54));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 16, 100));
        jLabel1.setText("Form Input Pesanan Laundry");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 450, 40));

        jPanel2.setBackground(new java.awt.Color(200, 217, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 65, 86));
        jLabel2.setText("Nama Pelanggan");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 150, 30));

        IsiNamaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiNamaPelangganActionPerformed(evt);
            }
        });
        jPanel2.add(IsiNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 310, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 65, 86));
        jLabel3.setText("Tanggal Masuk");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 65, 86));
        jLabel4.setText("Kategori");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, 30));

        IsiKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiKategoriActionPerformed(evt);
            }
        });
        jPanel2.add(IsiKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 310, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(47, 65, 86));
        jLabel5.setText("Berat Cucian (kg)");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 30));

        IsiBeratCucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiBeratCucianActionPerformed(evt);
            }
        });
        jPanel2.add(IsiBeratCucian, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 100, 30));

        jLabel7.setBackground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("Status Pesanan");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 700, 70));

        jPanel5.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 700, 70));

        IsiTanggal.setModel(new javax.swing.SpinnerDateModel());
        IsiTanggal.setEditor(new javax.swing.JSpinner.DateEditor(IsiTanggal, "dd/MM/yyyy"));
        jPanel2.add(IsiTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 250, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\prata\\OneDrive\\Dokumen\\project pbo\\waving_person-removebg-preview (1) (2).png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 810, 410));

        ButtonSimpan.setBackground(new java.awt.Color(47, 65, 86));
        ButtonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSimpan.setForeground(new java.awt.Color(255, 252, 255));
        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 520, 120, 40));

        ButtonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 120, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\prata\\OneDrive\\Dokumen\\project pbo\\formnew-transformed.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1246, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsiNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiNamaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiNamaPelangganActionPerformed

    private void IsiKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiKategoriActionPerformed

    private void IsiBeratCucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiBeratCucianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiBeratCucianActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        simpan();
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        new Data_Pelanggan_Offline().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReservasiOfflineGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JTextField IsiBeratCucian;
    private javax.swing.JComboBox<String> IsiKategori;
    private javax.swing.JTextField IsiNamaPelanggan;
    private javax.swing.JSpinner IsiTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
